
import { FileEntry } from './types';

export const DEFAULT_FILES: FileEntry[] = [
  {
    name: 'README.md',
    path: 'README.md',
    type: 'file',
    content: `# Obsidian Plugin Architect

This is an intelligent Integrated Development Environment (IDE) for building custom Obsidian plugins.

## How to build locally
1. Copy project files into your Obsidian plugin folder.
2. Run \`npm install\` command.
3. To generate the final bundle, run \`npm run build\`.
`
  },
  {
    name: 'package.json',
    path: 'package.json',
    type: 'file',
    content: `{
  "name": "obsidian-plugin-architect-project",
  "version": "1.0.0",
  "description": "An Obsidian plugin built with Architect Pro",
  "main": "main.js",
  "scripts": {
    "dev": "node esbuild.config.mjs",
    "build": "node esbuild.config.mjs production",
    "version": "node version-bump.mjs && git add manifest.json versions.json"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "@types/node": "^16.11.21",
    "builtin-modules": "^3.2.0",
    "esbuild": "0.17.11",
    "obsidian": "latest",
    "typescript": "4.9.5"
  }
}`
  },
  {
    name: 'tsconfig.json',
    path: 'tsconfig.json',
    type: 'file',
    content: `{
  "compilerOptions": {
    "baseUrl": ".",
    "inlineSourceMap": true,
    "inlineSources": true,
    "module": "ESNext",
    "target": "ES2018",
    "allowJs": true,
    "noImplicitAny": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "lib": ["DOM", "ES5", "ES6", "ES7"],
    "types": ["node"]
  },
  "include": ["main.ts"]
}`
  },
  {
    name: 'esbuild.config.mjs',
    path: 'esbuild.config.mjs',
    type: 'file',
    content: `import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = \`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/\`;

const prod = (process.argv[2] === "production");

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
}).catch(() => process.exit(1));`
  },
  {
    name: 'manifest.json',
    path: 'manifest.json',
    type: 'file',
    content: `{
  "id": "architect-sample-plugin",
  "name": "Architect Sample Plugin",
  "version": "1.0.0",
  "minAppVersion": "0.15.0",
  "description": "It's a professional plugin for Obsidian.",
  "author": "Architect Pro",
  "authorUrl": "https://obsidian.md",
  "isDesktopOnly": false
}`
  },
  {
    name: 'main.ts',
    path: 'main.ts',
    type: 'file',
    content: `import { App, Plugin, Notice } from 'obsidian';

export default class MyPlugin extends Plugin {
	async onload() {
		new Notice('Architect Plugin Loaded!');
	}

	onunload() {
		console.log('Plugin Unloaded');
	}
}`
  },
  {
    name: '.gitignore',
    path: '.gitignore',
    type: 'file',
    content: `node_modules/
main.js
.DS_Store
*.zip`
  },
  {
    name: 'styles.css',
    path: 'styles.css',
    type: 'file',
    content: `/* Add your CSS styles here */`
  }
];
